name: Deploy Production

on:
  workflow_dispatch:

jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run deploy deploy.sh
        run: |
          ./deploy.sh
        working-directory: ./server
