name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create .env
        run: |
          touch .env
          echo DB_USERNAME=${{ Secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ Secrets.DB_PASSWORD }} >> .env
          echo DB_HOST=${{ Secrets.DB_HOST }} >> .env
          echo SMART_HYDRATION_EMAIL=${{ Secrets.SMART_HYDRATION_EMAIL }} >> .env
          echo SMART_HYDRATION_PASSWORD=${{ Secrets.SMART_HYDRATION_PASSWORD }} >> .env
          echo JWT_SECRET=${{ Secrets.JWT_SECRET }} >> .env
          echo JWT_ALGORITHM=${{ Secrets.JWT_ALGORITHM }} >> .env
        working-directory: ./server

      - name: Add SSH key and known hosts
        run: |
          file=$(mktemp)
          echo "$SH_KEY_PAIR" > "$file"
          chmod 600 "$file"  # Ensure the SSH key has the correct permissions
          ssh-keyscan -H ec2-18-133-247-202.eu-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts
        env:
          SH_KEY_PAIR: ${{ Secrets.SH_KEY_PAIR }}

      - name: Run deploy script
        run: |
          ./deploy.sh "$file"
        working-directory: ./server
        env:
          SH_KEY_PAIR: ${{ Secrets.SH_KEY_PAIR }}
