name: Deploy Production

on:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create .env
              run: |
                  touch .env
                  echo USE_PRODUCTION_DB=$(echo 1) >> .env
                  echo PROD_DB_USERNAME=$(echo "${{ Secrets.DB_USERNAME }}" | xargs) >> .env
                  echo PROD_DB_PASSWORD=$(echo "${{ Secrets.DB_PASSWORD }}" | xargs)  >> .env
                  echo PROD_DB_HOST=$(echo "${{ Secrets.DB_HOST }}" | xargs) >> .env
                  echo SMART_HYDRATION_EMAIL=$(echo "${{ Secrets.SMART_HYDRATION_EMAIL }}" | xargs)  >> .env
                  echo SMART_HYDRATION_PASSWORD=$(echo "${{ Secrets.SMART_HYDRATION_PASSWORD }}" | xargs)  >> .env
                  echo JWT_SECRET=$(echo "${{ Secrets.JWT_SECRET }}" | xargs)  >> .env
                  echo JWT_ALGORITHM=$(echo "${{ Secrets.JWT_ALGORITHM }}" | xargs)  >> .env
                  echo PUSHER_APP_KEY=$(echo "${{ Secrets.PUSHER_APP_KEY }}" | xargs)  >> .env
                  echo PUSHER_APP_SECRET=$(echo "${{ Secrets.PUSHER_APP_SECRET }}" | xargs)  >> .env
                  echo PUSHER_APP_CLUSTER=$(echo "${{ Secrets.PUSHER_APP_CLUSTER }}" | xargs)  >> .env
                  echo SES_USER_ID=$(echo "${{ Secrets.SES_USER_ID }}" | xargs)  >> .env
                  echo SES_PASSWORD=$(echo "${{ Secrets.SES_PASSWORD }}" | xargs)  >> .env
                  echo SES_HOST_ADDRESS=$(echo "${{ Secrets.SES_HOST_ADDRESS }}" | xargs)  >> .env
                  chmod 777 .env
              working-directory: ./server

            - name: Run deploy deploy.sh
              shell: bash
              run: |
                  file=$(mktemp)
                  echo -n "${{ Secrets.SH_KEY_PAIR }}" >> "$file"
                  chmod 600 "$file"
                  ./deploy.sh "$file"
              working-directory: ./server
